# Site Settings
title: Abdul Manan Abbasi
logo: /assets/img/headshot_circle.png  # Add your profile picture or logo
description: Data Scientist | Machine Learning Engineer | Problem Solver
baseurl: ""  # Leave empty if hosting at the root of your domain
url: "https://yourwebsite.com"  # Replace with your actual website URL

# Theme and Design
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Enable download buttons for resume or portfolio
show_downloads: true

# Customize navigation links
navbar:
  links:
    - name: About
      url: /about
    - name: Projects
      url: /projects
    - name: Blog
      url: /blog
    - name: Contact
      url: /contact

# Add social media links
social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/your-profile
    icon: linkedin  # Use Font Awesome icons if supported
  - name: GitHub
    url: https://github.com/your-username
    icon: github
  - name: Email
    url: mailto:your.email@example.com
    icon: envelope

# Custom footer
footer:
  message: "© 2024 Abdul Manan Abbasi. All rights reserved."
  links:
    - name: Privacy Policy
      url: /privacy
    - name: Terms of Use
      url: /terms

# Optional: Add Google Analytics for tracking
google_analytics: UA-XXXXX-X  # Replace with your Google Analytics ID

# Optional: Add a custom color scheme
colors:
  primary: "#2c3e50"  # Dark blue
  secondary: "#3498db"  # Light blue
  accent: "#e74c3c"  # Red

# Optional: Add a blog configuration
blog:
  title: My Data Science Blog
  description: Insights, tutorials, and updates on data science, machine learning, and AI.
  paginate: 5
  paginate_path: "/blog/page:num/"

# Optional: Add a custom 404 page
error_page: /404.html
