title: Abdul Manan Abbasi
#logo: /assets/img/headshot_circle.png  # Add your profile picture or logo
description: Data Scientist | Machine Learning Engineer | Problem Solver
#show_downloads: true  # Enable download buttons for resume or portfolio
theme: jekyll-theme-minimal
